### ISSUE TITLE
Groovy implementation

### ISSUE THREAD

**Issue by benzen** [caolan/magery#4]
I've done a groovy implementation.

Here it is:
https://github.com/benzen/magery-groovy/tree/master

**Comment by caolan** [comment]
Wow! that's great 👍 

You might find some HTML normalisation is necessary for the tests to work smoothly... just going off what's in your README, I don't know groovy and haven't attempted to run these yet.

In the meantime feel free to add your groovy implementation to the magery README, the pull request will be accepted :)

**Comment by caolan** [comment]
And, forgive my ignorance, but does this mean your implementation is available to other JVM languages?

**Comment by benzen** [comment]
Yes once compiled it feels the same as any java lib.
So of course if your are using clojure it will feel weird, but a simple wrapper will do the trick for such a language.

**Comment by benzen** [comment]
About the html normalisation.
I would prefer getting you feedback on my comments/issues before going forward on that path.

Plus I don’t want to maintain a separate test suite, which could be out of sync with the reference one.

**Comment by caolan** [comment]
I do the normalisation step in my test runner (comparing parsed HTML trees instead of the string output). I think this has made me a bit blind to some formatting/whitespace issues in the test suite though, so I'm happy to accept pull requests to make them more predictable. If it's possible to compare raw string output, that would make it easier to port.
